/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FHEAMMInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "appliedFeeRatio"
      | "appliedTickSpacing"
      | "applyParameters"
      | "confidentialProtocolId"
      | "getActionAt"
      | "getActionsLength"
      | "getAggregates"
      | "getMyPosition"
      | "getSuggestions"
      | "owner"
      | "renounceOwnership"
      | "submitPosition"
      | "submitVolatility"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ParametersApplied"
      | "PositionSubmitted"
      | "VolatilitySubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "appliedFeeRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "appliedTickSpacing",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "applyParameters",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActionAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActionsLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAggregates",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyPosition",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSuggestions",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitPosition",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitVolatility",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "appliedFeeRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "appliedTickSpacing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActionAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActionsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAggregates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSuggestions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitVolatility",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParametersAppliedEvent {
  export type InputTuple = [feeRatio: BigNumberish, tickSpacing: BigNumberish];
  export type OutputTuple = [feeRatio: bigint, tickSpacing: bigint];
  export interface OutputObject {
    feeRatio: bigint;
    tickSpacing: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionSubmittedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VolatilitySubmittedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FHEAMM extends BaseContract {
  connect(runner?: ContractRunner | null): FHEAMM;
  waitForDeployment(): Promise<this>;

  interface: FHEAMMInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  appliedFeeRatio: TypedContractMethod<[], [bigint], "view">;

  appliedTickSpacing: TypedContractMethod<[], [bigint], "view">;

  applyParameters: TypedContractMethod<
    [feeRatioClear: BigNumberish, tickSpacingClear: BigNumberish],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getActionAt: TypedContractMethod<[index: BigNumberish], [string], "view">;

  getActionsLength: TypedContractMethod<[], [bigint], "view">;

  getAggregates: TypedContractMethod<
    [],
    [
      [string, string, string, string] & {
        aggLiquidity: string;
        sumLower: string;
        sumUpper: string;
        twoTimesNumPositions: string;
      }
    ],
    "view"
  >;

  getMyPosition: TypedContractMethod<
    [],
    [
      [string, string, string, boolean] & {
        liquidity: string;
        priceLower: string;
        priceUpper: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  getSuggestions: TypedContractMethod<
    [],
    [[string, string] & { feeRatio: string; tickSpacing: string }],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  submitPosition: TypedContractMethod<
    [
      encLiquidity: BytesLike,
      encPriceLower: BytesLike,
      encPriceUpper: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  submitVolatility: TypedContractMethod<
    [encVolatility: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "appliedFeeRatio"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "appliedTickSpacing"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "applyParameters"
  ): TypedContractMethod<
    [feeRatioClear: BigNumberish, tickSpacingClear: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getActionAt"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getActionsLength"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAggregates"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, string] & {
        aggLiquidity: string;
        sumLower: string;
        sumUpper: string;
        twoTimesNumPositions: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMyPosition"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, boolean] & {
        liquidity: string;
        priceLower: string;
        priceUpper: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSuggestions"
  ): TypedContractMethod<
    [],
    [[string, string] & { feeRatio: string; tickSpacing: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitPosition"
  ): TypedContractMethod<
    [
      encLiquidity: BytesLike,
      encPriceLower: BytesLike,
      encPriceUpper: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitVolatility"
  ): TypedContractMethod<
    [encVolatility: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ParametersApplied"
  ): TypedContractEvent<
    ParametersAppliedEvent.InputTuple,
    ParametersAppliedEvent.OutputTuple,
    ParametersAppliedEvent.OutputObject
  >;
  getEvent(
    key: "PositionSubmitted"
  ): TypedContractEvent<
    PositionSubmittedEvent.InputTuple,
    PositionSubmittedEvent.OutputTuple,
    PositionSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "VolatilitySubmitted"
  ): TypedContractEvent<
    VolatilitySubmittedEvent.InputTuple,
    VolatilitySubmittedEvent.OutputTuple,
    VolatilitySubmittedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ParametersApplied(uint32,uint32)": TypedContractEvent<
      ParametersAppliedEvent.InputTuple,
      ParametersAppliedEvent.OutputTuple,
      ParametersAppliedEvent.OutputObject
    >;
    ParametersApplied: TypedContractEvent<
      ParametersAppliedEvent.InputTuple,
      ParametersAppliedEvent.OutputTuple,
      ParametersAppliedEvent.OutputObject
    >;

    "PositionSubmitted(address)": TypedContractEvent<
      PositionSubmittedEvent.InputTuple,
      PositionSubmittedEvent.OutputTuple,
      PositionSubmittedEvent.OutputObject
    >;
    PositionSubmitted: TypedContractEvent<
      PositionSubmittedEvent.InputTuple,
      PositionSubmittedEvent.OutputTuple,
      PositionSubmittedEvent.OutputObject
    >;

    "VolatilitySubmitted(address)": TypedContractEvent<
      VolatilitySubmittedEvent.InputTuple,
      VolatilitySubmittedEvent.OutputTuple,
      VolatilitySubmittedEvent.OutputObject
    >;
    VolatilitySubmitted: TypedContractEvent<
      VolatilitySubmittedEvent.InputTuple,
      VolatilitySubmittedEvent.OutputTuple,
      VolatilitySubmittedEvent.OutputObject
    >;
  };
}
